# Sahi docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app 
      - ./Database:/app/Database
      - ./Ai_Services:/app/Ai_Services
    env_file:
      - .env
    environment:
      - DOCKER_ENV="true" 
    depends_on:
      - database 

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    env_file:
      - .env 
    ports:
      - "5432:5432" 
    
volumes:
  postgres_data: